### ISSUE TITLE
The database not install

### ISSUE THREAD

**Issue by xarthurnunes** [MisterCalvin/amxbans#1]
When I will install, put all data correctly but when I will test the database connection I get error 500 and get this error_log

[11-Dec-2024 08:55:35 America/Fortaleza] PHP Warning:  Undefined array key "dbhost" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 463
[11-Dec-2024 08:55:35 America/Fortaleza] PHP Warning:  Undefined array key "dbuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 464
[11-Dec-2024 08:55:35 America/Fortaleza] PHP Warning:  Undefined array key "dbpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 465
[11-Dec-2024 08:55:35 America/Fortaleza] PHP Warning:  Undefined array key "dbdb" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 466
[11-Dec-2024 08:55:35 America/Fortaleza] PHP Warning:  Undefined array key "dbprefix" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 467
[11-Dec-2024 08:55:35 America/Fortaleza] PHP Warning:  Undefined array key "adminuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 468
[11-Dec-2024 08:55:35 America/Fortaleza] PHP Warning:  Undefined array key "adminpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 469
[11-Dec-2024 08:55:35 America/Fortaleza] PHP Warning:  Undefined array key "adminemail" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 470
[11-Dec-2024 08:56:16 America/Fortaleza] PHP Warning:  Undefined array key "dbhost" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 463
[11-Dec-2024 08:56:16 America/Fortaleza] PHP Warning:  Undefined array key "dbuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 464
[11-Dec-2024 08:56:16 America/Fortaleza] PHP Warning:  Undefined array key "dbpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 465
[11-Dec-2024 08:56:16 America/Fortaleza] PHP Warning:  Undefined array key "dbdb" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 466
[11-Dec-2024 08:56:16 America/Fortaleza] PHP Warning:  Undefined array key "dbprefix" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 467
[11-Dec-2024 08:56:16 America/Fortaleza] PHP Warning:  Undefined array key "adminuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 468
[11-Dec-2024 08:56:16 America/Fortaleza] PHP Warning:  Undefined array key "adminpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 469
[11-Dec-2024 08:56:16 America/Fortaleza] PHP Warning:  Undefined array key "adminemail" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 470
[11-Dec-2024 08:56:24 America/Fortaleza] PHP Warning:  Undefined array key "dbhost" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 463
[11-Dec-2024 08:56:24 America/Fortaleza] PHP Warning:  Undefined array key "dbuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 464
[11-Dec-2024 08:56:24 America/Fortaleza] PHP Warning:  Undefined array key "dbpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 465
[11-Dec-2024 08:56:24 America/Fortaleza] PHP Warning:  Undefined array key "dbdb" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 466
[11-Dec-2024 08:56:24 America/Fortaleza] PHP Warning:  Undefined array key "dbprefix" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 467
[11-Dec-2024 08:56:24 America/Fortaleza] PHP Warning:  Undefined array key "adminuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 468
[11-Dec-2024 08:56:24 America/Fortaleza] PHP Warning:  Undefined array key "adminpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 469
[11-Dec-2024 08:56:24 America/Fortaleza] PHP Warning:  Undefined array key "adminemail" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 470
[11-Dec-2024 08:56:27 America/Fortaleza] PHP Warning:  Undefined array key "dbhost" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 463
[11-Dec-2024 08:56:27 America/Fortaleza] PHP Warning:  Undefined array key "dbuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 464
[11-Dec-2024 08:56:27 America/Fortaleza] PHP Warning:  Undefined array key "dbpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 465
[11-Dec-2024 08:56:27 America/Fortaleza] PHP Warning:  Undefined array key "dbdb" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 466
[11-Dec-2024 08:56:27 America/Fortaleza] PHP Warning:  Undefined array key "dbprefix" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 467
[11-Dec-2024 08:56:27 America/Fortaleza] PHP Warning:  Undefined array key "adminuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 468
[11-Dec-2024 08:56:27 America/Fortaleza] PHP Warning:  Undefined array key "adminpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 469
[11-Dec-2024 08:56:27 America/Fortaleza] PHP Warning:  Undefined array key "adminemail" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 470
[11-Dec-2024 08:56:50 America/Fortaleza] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'netstrik_amxbans.amx_bans' doesn't exist in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php:314
Stack trace:
#0 /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php(314): mysqli->query('SHOW COLUMNS FR...')
#1 {main}
  thrown in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 314

**Comment by MisterCalvin** [comment]
Will you give me the following details:
- OS Version (for Debian based systems, `cat /etc/os-release`)
-  Is this a new AMXBans database? Or are you trying to import a database from a previous version of AMXBans?
- Are you using Docker? If so, what is your Docker version (`docker --version`)
- If you're not using Docker, what are the versions for: your web server, MySQL (`mysql --version` or `mariadb --version`), and PHP (`php --version`, I will also need your installed modules, `php -m`)

**Comment by xarthurnunes** [comment]
Is in cpanel, is a new amxbans database
PHP Version | 8.3.11
MySQL Version | mysqlnd 8.3.11

**Comment by xarthurnunes** [comment]
@MisterCalvin are you have some idea about?

**Comment by MisterCalvin** [comment]
- Double check your MySQL database credentials in cPanel
   - Ensure the database user has ALL privileges on the database
   - Make sure the database exists before running setup
   
 Also try:
   - Starting with a fresh database (no existing tables)
   - Clear your browser cache and cookies
   - Go through setup step-by-step without skipping any fields
   - On the database configuration page, try using 'localhost' for the database host
   - Make sure to use a unique prefix for the tables
   
   Let me know if the issue persists after trying these steps

**Comment by xarthurnunes** [comment]
Hello,

Realized all that you tell me about I got the same error:

![Screenshot_2024-12-14-18-09-28-323_com android chrome](https://github.com/user-attachments/assets/f88872d3-b60e-4163-8f43-18f59be92914)
![Screenshot_2024-12-14-18-10-55-815_com android chrome](https://github.com/user-attachments/assets/19b1e2c8-53e2-4daa-be86-9b828a761b86)
![Screenshot_2024-12-14-18-28-52-138_com android chrome](https://github.com/user-attachments/assets/dbabed3d-6f24-4ba3-a5fd-3d5822de3bc0)

Also I changed the browser set a new dB, new user, etc.

If you want I can send to you the address and the access to ftp to you can try it.

**Comment by MisterCalvin** [comment]
Will you give me the full output of the following logs after doing a fresh installation:
- Web server
- MySQL server
I just spun up a new instance of this project and it installed fine, so I am assuming there is a configuration issue somewhere

**Comment by xarthurnunes** [comment]
Webserver log:
[14-Dec-2024 18:26:53 America/Fortaleza] PHP Warning:  Undefined array key "dbhost" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 463
[14-Dec-2024 18:26:53 America/Fortaleza] PHP Warning:  Undefined array key "dbuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 464
[14-Dec-2024 18:26:53 America/Fortaleza] PHP Warning:  Undefined array key "dbpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 465
[14-Dec-2024 18:26:53 America/Fortaleza] PHP Warning:  Undefined array key "dbdb" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 466
[14-Dec-2024 18:26:53 America/Fortaleza] PHP Warning:  Undefined array key "dbprefix" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 467
[14-Dec-2024 18:26:53 America/Fortaleza] PHP Warning:  Undefined array key "adminuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 468
[14-Dec-2024 18:26:53 America/Fortaleza] PHP Warning:  Undefined array key "adminpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 469
[14-Dec-2024 18:26:53 America/Fortaleza] PHP Warning:  Undefined array key "adminemail" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 470
[14-Dec-2024 18:27:02 America/Fortaleza] PHP Warning:  Undefined array key "dbhost" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 463
[14-Dec-2024 18:27:02 America/Fortaleza] PHP Warning:  Undefined array key "dbuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 464
[14-Dec-2024 18:27:02 America/Fortaleza] PHP Warning:  Undefined array key "dbpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 465
[14-Dec-2024 18:27:02 America/Fortaleza] PHP Warning:  Undefined array key "dbdb" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 466
[14-Dec-2024 18:27:02 America/Fortaleza] PHP Warning:  Undefined array key "dbprefix" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 467
[14-Dec-2024 18:27:02 America/Fortaleza] PHP Warning:  Undefined array key "adminuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 468
[14-Dec-2024 18:27:02 America/Fortaleza] PHP Warning:  Undefined array key "adminpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 469
[14-Dec-2024 18:27:02 America/Fortaleza] PHP Warning:  Undefined array key "adminemail" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 470
[14-Dec-2024 18:27:05 America/Fortaleza] PHP Warning:  Undefined array key "dbhost" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 463
[14-Dec-2024 18:27:05 America/Fortaleza] PHP Warning:  Undefined array key "dbuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 464
[14-Dec-2024 18:27:05 America/Fortaleza] PHP Warning:  Undefined array key "dbpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 465
[14-Dec-2024 18:27:05 America/Fortaleza] PHP Warning:  Undefined array key "dbdb" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 466
[14-Dec-2024 18:27:05 America/Fortaleza] PHP Warning:  Undefined array key "dbprefix" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 467
[14-Dec-2024 18:27:05 America/Fortaleza] PHP Warning:  Undefined array key "adminuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 468
[14-Dec-2024 18:27:05 America/Fortaleza] PHP Warning:  Undefined array key "adminpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 469
[14-Dec-2024 18:27:05 America/Fortaleza] PHP Warning:  Undefined array key "adminemail" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 470
[14-Dec-2024 18:27:08 America/Fortaleza] PHP Warning:  Undefined array key "dbhost" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 463
[14-Dec-2024 18:27:08 America/Fortaleza] PHP Warning:  Undefined array key "dbuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 464
[14-Dec-2024 18:27:08 America/Fortaleza] PHP Warning:  Undefined array key "dbpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 465
[14-Dec-2024 18:27:08 America/Fortaleza] PHP Warning:  Undefined array key "dbdb" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 466
[14-Dec-2024 18:27:08 America/Fortaleza] PHP Warning:  Undefined array key "dbprefix" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 467
[14-Dec-2024 18:27:08 America/Fortaleza] PHP Warning:  Undefined array key "adminuser" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 468
[14-Dec-2024 18:27:08 America/Fortaleza] PHP Warning:  Undefined array key "adminpass" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 469
[14-Dec-2024 18:27:08 America/Fortaleza] PHP Warning:  Undefined array key "adminemail" in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 470
[14-Dec-2024 18:28:47 America/Fortaleza] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'netstrik_amxbans.amx_bans' doesn't exist in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php:314
Stack trace:
#0 /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php(314): mysqli->query('SHOW COLUMNS FR...')
#1 {main}
  thrown in /home2/netstrike/public_html/csbrteam.com.br/amxbans/setup.php on line 314
  
  
  Unfortunatelly the mysql logs are not available in the cpanel hosting
  
  @MisterCalvin

**Comment by xarthurnunes** [comment]
I solved that @MisterCalvin thanks for your attention.
